name: Reusable CI - Generic
#pipeline de integración continua genérica que se puede reutilizar en diferentes proyectos. Permite configurar comandos de instalación, linting, testing y build, así como la configuración de entornos de desarrollo para Node.js, Python y Java. Además, maneja la generación y carga de artefactos de build y reportes de cobertura.
on:
  workflow_call:
    inputs:
      working-directory:
        required: false
        type: string
        default: '.'
      run-tests:
        required: false
        type: boolean
        default: true
      install-command:
        required: true
        type: string
      lint-command:
        required: false
        type: string
        default: ''
      test-command:
        required: false
        type: string
        default: ''
      build-command:
        required: false
        type: string
        default: ''
      artifact-path:
        required: false
        type: string
        default: 'dist/'
      setup-node:
        required: false
        type: boolean
        default: false
      node-version:
        required: false
        type: string
        default: '20'
      setup-python:
        required: false
        type: boolean
        default: false
      python-version:
        required: false
        type: string
        default: '3.12'
      setup-java:
        required: false
        type: boolean
        default: false
      java-version:
        required: false
        type: string
        default: '21'
      docker-image-name:
        required: false
        type: string
        default: ''    
      dockerfile-path:                
        type: string
        default: 'Dockerfile'
           
    secrets:
      KUBE_CONFIG:
          required: false
      DOCKERHUB_USERNAME:        
        required: false
      DOCKERHUB_TOKEN:           
        required: false
      PACKAGE_TOKEN:
        required: false
      SONAR_TOKEN:             
        required: false  
    outputs:
      artifact-name:
        description: "Nombre del artefacto generado"
        value: ${{ jobs.build.outputs.artifact-name }}



jobs:
#chequeo de código con linters, se ejecuta solo si lint-command no está vacío. Además, se asegura de que se haya configurado al menos un entorno de desarrollo (Node.js, Python o Java) para evitar ejecutar linters sin un entorno adecuado.
  lint:
    runs-on: ubuntu-latest
    if: ${{ inputs.lint-command != '' }}
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        if: ${{ inputs.setup-node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'npm'

      - name: Setup Python
        if: ${{ inputs.setup-python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
          cache: 'pip'

      - name: Setup Java
        if: ${{ inputs.setup-java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java-version }}
          distribution: 'temurin'
          cache: 'maven'

      - name: Install dependencies
        run: ${{ inputs.install-command }}
        env:
          PACKAGE_TOKEN: ${{ secrets.PACKAGE_TOKEN }}

      - name: Run lint
        run: ${{ inputs.lint-command }}

      - name: SonarCloud analysis
        run: |
          mvn sonar:sonar \
            -Dsonar.projectKey=hakimsa_bakend-mgt \
            -Dsonar.organization=hakimsa-1 \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}


# test unitarios, de integración o end-to-end dependiendo del comando configurado en test-command. Solo se ejecuta si run-tests es true y test-command no está vacío. Además, se asegura de que lint-command no esté vacío para evitar ejecutar tests si no se ha configurado un comando de linting.
  test:
    runs-on: ubuntu-latest
    needs: lint
    if: ${{ inputs.run-tests && inputs.test-command != '' && inputs.lint-command != '' }}
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    steps:
      - uses: actions/checkout@v4

#setup de nodejs
      - name: Setup Node.js
        if: ${{ inputs.setup-node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'npm'

#setup de python
      - name: Setup Python
        if: ${{ inputs.setup-python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
          cache: 'pip'

#setup de java
      - name: Setup Java
        if: ${{ inputs.setup-java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java-version }}
          distribution: 'temurin'
          cache: 'maven'

      - name: Install dependencies
        run: ${{ inputs.install-command }}
        env:
          PACKAGE_TOKEN: ${{ secrets.PACKAGE_TOKEN }}

      - name: Run tests
        run: ${{ inputs.test-command }}

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/


#build images 
  build:
    runs-on: ubuntu-latest
    needs: [lint, test] 
    if: ${{ !failure() && !cancelled() && inputs.build-command != '' }}
    outputs:
      artifact-name: ${{ steps.set-output.outputs.artifact-name }}
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    steps:
      - uses: actions/checkout@v4
#step para configurar Node.js, se ejecuta solo si setup-node es true. Utiliza la acción oficial de setup-node para configurar la versión de Node.js especificada en node-version y habilitar el cache de npm para acelerar la instalación de dependencias en futuras ejecuciones.
      - name: Setup Node.js
        if: ${{ inputs.setup-node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'npm'
#step para configurar Python, se ejecuta solo si setup-python es true. Utiliza la acción oficial de setup-python para configurar la versión de Python especificada en python-version y habilitar el cache de pip para acelerar la instalación de dependencias en futuras ejecuciones.
      - name: Setup Python
        if: ${{ inputs.setup-python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
          cache: 'pip'
#step para configurar Java, se ejecuta solo si setup-java es true. Utiliza la acción oficial de setup-java para configurar la versión de Java especificada en java-version, utilizando la distribución Temurin y habilitando el cache de Maven para acelerar la construcción del proyecto en futuras ejecuciones.
      - name: Setup Java
        if: ${{ inputs.setup-java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java-version }}
          distribution: 'temurin'
          cache: 'maven'

      - name: Install dependencies
        run: ${{ inputs.install-command }}
        env:
          PACKAGE_TOKEN: ${{ secrets.PACKAGE_TOKEN }}


#build artifact, se ejecuta solo si build-command no está vacío. Además, se asegura de que los pasos de linting y testing hayan sido exitosos antes de ejecutar el comando de build para evitar construir artefactos si hay errores en el código o en los tests.
      - name: Build
        run: ${{ inputs.build-command }}

      - name: Set artifact name
        id: set-output
        run: echo "artifact-name=build-${{ github.sha }}" >> $GITHUB_OUTPUT

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ github.sha }}
          path: ${{ inputs.working-directory }}/${{ inputs.artifact-path }}
          retention-days: 7

#  Docker Hub -build image and push to registry, se ejecuta solo si docker-image-name no está vacío. Utiliza la acción oficial de docker/login-action para autenticar con Docker Hub utilizando las credenciales almacenadas en los secretos DOCKERHUB_USERNAME y DOCKERHUB_TOKEN. Luego, utiliza la acción docker/build-push-action para construir la imagen de Docker a partir del contexto especificado en working-directory y etiquetarla con el nombre de imagen proporcionado en docker-image-name, incluyendo tanto la etiqueta "latest" como una etiqueta específica basada en el SHA del commit actual. Finalmente, se empuja la imagen construida al registro de Docker Hub.
      - name: Debug secrets
        if: ${{ inputs.docker-image-name != '' }}
        run: |
          echo "Username is empty: ${{ secrets.DOCKERHUB_USERNAME == '' }}"
          echo "Token is empty: ${{ secrets.DOCKERHUB_TOKEN == '' }}"
      - name: Login to Docker Hub
        if: ${{ inputs.docker-image-name != '' }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} 
          password: ${{ secrets.DOCKERHUB_TOKEN}}

      - name: Build Docker image
        if: ${{ inputs.docker-image-name != '' }}
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.working-directory }}
          file: ${{ inputs.dockerfile-path }}
          push: false
          tags: |
            ${{secrets.DOCKERHUB_USERNAME}}/${{ inputs.docker-image-name }}:latest
            ${{secrets.DOCKERHUB_USERNAME}}/${{ inputs.docker-image-name }}:${{ github.sha }}

#Push Docker image, se ejecuta solo si docker-image-name no está vacío. Utiliza la acción docker/build-push-action para empujar la imagen de Docker previamente construida al registro de Docker Hub, utilizando las mismas etiquetas que se asignaron durante el paso de construcción.
      - name: Push Docker image
        if: ${{ inputs.docker-image-name != '' }}
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.working-directory }}
          file: ${{ inputs.dockerfile-path }}
          push: true
          tags: |
             ${{secrets.DOCKERHUB_USERNAME}}/${{ inputs.docker-image-name }}:latest
             ${{secrets.DOCKERHUB_USERNAME}}/${{ inputs.docker-image-name }}:${{ github.sha }}          